### PR TITLE
Create ESPHome documentation page

### PR DESCRIPTION
**Pull request by nagyrobi**
page to be added to `esphome-docs/components`

ESPHome moderators want this component in as a PR:
https://discord.com/channels/429907082951524364/937081638406463558/937366709260668939

### CODE REVIEW

**Comment by andyboeh** [comment]
I don't get the advantage of having this file over the README?

**Comment by nagyrobi** [comment]
It has some syntax requirements to blend into the manual.
Just wanted to give you a hand.

**Comment by andyboeh** [comment]
I'm sorry but I have no idea what you're talking about. Which syntax requirements? What for? What is this discord link (I don't have a Discord account, it doesn't open)?

**Comment by nagyrobi** [comment]
ESPHome main authors seem to like this component. Discord is the platform chosen by them to have live chat support. I made some pictures of the device I made + posted a link to this repo in their Discord chat, and asked them to take a look, would it be worth merging.

One of the devs said he thought there's already a PR with this component done... He admitted that he was also thinking quite a lot on how to implement DMX earlier. Looks like he's happy that someone has finally done it. He has experience with DMX based on his statements, so he understands the speciality of this case. 

To submit code in ESPHome one has to also submit documentation PRs in parrallel, to the main site https://esphome.io/ 
That site has its own syntax, it's also hosted on github, but those are not the simple .md files. Also if you follow a bit the documentation of the other components, you'll se the level of detail they explain things - that's what I thought maybe I give a hand by preparing a first draft myself. Example for specific devices is rarely present in the main documentation, that's the place named cookbook - where I prepared the example with my fixtures.

**Comment by andyboeh** [comment]
Sorry, I have no interest in creating a PR and getting this merged, for several reasons:

1. As mentioned in https://github.com/esphome/feature-requests/issues/319#issuecomment-1018224524_ I don't think this can be merged in its current state. It's too hacky.
2. Implementing this cleanly means going down to the Arduino library level and adding the necessary commands for sending breaks there. This is a long road that I'm not willing to go (see 3. below)
3. I don't have the necessary resources to support it long-term - and that's the real and biggest problem.

I'm going to support anybody else who creates a PR upstream - feel free to do so. Closing now.

**Comment by nagyrobi** [comment]
So you don't mind if I do the PR instead?

**Comment by andyboeh** [comment]
No, of course not - feel free to do so. I'm not going to create a PR.

**Comment by nagyrobi** [comment]
Thank you.

**Pull request closed without merging**
